package eu.europa.ted.eforms.sdk.analysis.drools;

unit SdkUnit;

import eu.europa.ted.eforms.sdk.domain.field.Field;
import eu.europa.ted.eforms.sdk.domain.field.XmlStructureNode;

// TEDEFO-2205: Xpath absolute uniqueness is verified.
//  For fields.json file:
//    The xpathAbsolute of a field should not be equal to the xpathAbsolute of a node
rule "Xpath absolute uniqueness is verified"
when
  /fields[ $f: this, $fieldId : id, $xpathAbsoluteField: xpathAbsolute ];
  /nodes[ $n: this, $nodeId : id, $xpathAbsoluteNode: xpathAbsolute ]
  eval($xpathAbsoluteField == $xpathAbsoluteNode)
then
  results.add(new ValidationResult($f, "xpath absolute are equal for field " + $fieldId + ", node " + $nodeId, ValidationStatusEnum.ERROR));
end
