package eu.europa.ted.eforms.sdk.analysis.drools;

unit SdkUnit;

import eu.europa.ted.eforms.sdk.domain.field.Field;
import eu.europa.ted.eforms.sdk.domain.field.XmlStructureNode;

rule "Fields.json has correct SDK version"
when
  /fieldsAndNodesMetadata[ $f: this, $version: sdkVersion, $version != "eforms-sdk-" + sdkMetadata.version ]
then
  results.add(new ValidationResult($f, "the value " + $version + " in sdkVersion is incorrect", ValidationStatusEnum.ERROR));
end

rule "Every node has at least one child"
when
  /nodes[ $n: this, $nodeId : id ]
  not (exists /nodes[ parentId == $nodeId ] or /fields[ parentId == $nodeId ])
then
  results.add(new ValidationResult($n, "node has no child node or field", ValidationStatusEnum.ERROR));
end

// TEDEFO-2205: Xpath absolute uniqueness is verified.
//  For fields.json file:
//    The xpathAbsolute of a field should not be equal to the xpathAbsolute of a node
rule "Xpath absolute uniqueness is verified"
when
  /fields[ $f: this, $fieldId : id, $xpathAbsoluteField: xpathAbsolute ];
  /nodes[ $n: this, $nodeId : id, $xpathAbsoluteNode: xpathAbsolute ]
  eval($xpathAbsoluteField == $xpathAbsoluteNode)
then
  results.add(new ValidationResult($f, "xpath absolute are equal for field " + $fieldId + ", node " + $nodeId, ValidationStatusEnum.ERROR));
end
